
[tasks.build]
command = "cargo"
args = ["build"]

[tasks.post-build]
command = "cargo"
args = ["build", "--manifest-path=build\\Cargo.toml"]

[tasks.run-post-build]
command = "cargo"
args = ["run", "--manifest-path=build\\Cargo.toml"]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.dev]
dependencies = ["build", "post-build", "run-post-build", "run"]